# Change these first
owner: thezoggy # Your GitHub organization or username, where this repository lives
repo: status-thexem # The name of this repository

sites:
  - name: theXEM
    url: https://thexem.info

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.thexem.info
  logoUrl: https://raw.githubusercontent.com/thezoggy/status-thexem/master/assets/logo.svg
  theme: ocean
  name: " "
  introTitle: "thexem.info status"
  introMessage: "To report an issue join #xem on irc.libera.chat or #xem on sonarr's [discord](https://discord.sonarr.tv/)"
  css: "nav > div { justify-content: center !important; }; .graph { -webkit-mask-image: none !important; mask-image: none !important };"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
robotsText: "User-agent: * \n Disallow: /"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
